[package]
name = "airc"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
sarge = "7.0"
thiserror = "1.0.50"
